export const projects = [
  {
    title: 'Portfolio Web',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: require('../assets/proj/portfolio.PNG'),
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    color: '#457b9d',
    id: 0,
  },
  {
    title: 'Weather Broadcast ',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: require('../assets/proj/after.PNG'),
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',color: '#457b9d',
    id: 1,
  },
  {
    title: 'Game Web',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: require('../assets/proj/Game.PNG'),
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',color: '#457b9d',
    id: 2,
  },
  {
    title: 'TodoApp Web',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: require('../assets/proj/proj4.PNG'),
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',color: '#d0bb57',
    id: 3,
  },
];