export const projects = [
  {
    title: 'Portfolio Web',
    description: "This website. It has shown some of my projects and something that I want to share. It have included interesting features such as animated model/icons, dark mode, language mode, and tsparticles.",
      image: require('../assets/proj/portfolio.PNG'),
      tags: ['React', 'Redux','ThreeJs'],
    source: 'https://google.com',
    visit: 'https://google.com',
    color: '#457b9d',
    id: 0,
  },
  {
    title: 'Weather Broadcast ',
    description:"A website that implements a interactive mario-style via html canvas and utilises geolocation & OpenWeather api to give users the weather info of current location.",
    image: require('../assets/proj/after.PNG'),
    tags: ['JavaScript', 'Canvas', 'API'],
    source: 'https://google.com',
    visit: 'https://google.com',color: '#457b9d',
    id: 1,
  },
  {
    title: 'Game Web',
    description: "A website that includes small games such as Tic Tac Toe, Slido, and etc. It has shown a strong usage of react hooks.",
      image: require('../assets/proj/Game.PNG'),
      tags: ['React', 'Hooks'],
    source: 'https://google.com',
    visit: 'https://google.com',color: '#457b9d',
    id: 2,
  },
  {
    title: 'TodoApp Web',
    description: "A full stack project that is implemented via (MongoDB, Express, React, Node). Intresting features include jwttoken, bcrypt, Formspree, ics-file and etc.",
    image: require('../assets/proj/proj4.PNG'),
    tags: ['Mongo', 'Express', 'React', 'Node', 'MUI'],
    source: 'https://google.com',
    visit: 'https://google.com',color: '#d0bb57',
    id: 3,
  },
  {
    title: 'MyReact',
    description: "This project has replicated a very simplified version of React focused on diffing on the virtual DOM and rendering on real DOM.",
    image: require('../assets/proj/proj4.PNG'),
    tags: ['JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',color: '#58201e',
    id: 4,
  },
];