export const photos = [
  {
    src: require('../assets/pic/myphoto1.jpg'),
    width: 5,
    height: 3,
    title: 'La Perouse, New South Wales, Australia',
  },
  {
    src: require('../assets/pic/myphoto2.jpg'),
    width: 5,
    height: 3,
    title: 'Kensington, New South Wales, Australia',
  },
  {
    src: require('../assets/pic/myphoto5.jpg'),
    width: 5,
    height: 3,
    title: 'Watsons Bay, New South Wales, Australia',
  },
  {
    src: require('../assets/pic/myphoto3.jpg'),
    width: 5,
    height: 3,
    title: 'Circular Quay, New South Wales, Australia',
  },
  {
    src: require('../assets/pic/myphoto16.jpg'),
    width: 5,
    height: 3,
    title: 'Launceston, Tasmania, Australia',
  },
  {
    src: require('../assets/pic/myphoto19.jpg'),
    width: 5,
    height: 3,
    title: 'MONA Museum, Hobart, Tasmania, Australia',
  },
  {
    src: require('../assets/pic/myphoto6.jpg'),
    width: 5,
    height: 3,
    title: 'Langkawi, Malaysia',
  },
  {
    src: require('../assets/pic/myphoto7.jpg'),
    width: 5,
    height: 3,
    title: 'Kuala Lumpur, Malaysia',
  },
  // {
  //   src: require('../assets/pic/myphoto8.jpg'),
  //   width: 5,
  //   height: 3,
  //   title: 'Singapore',
  // },
  {
    src: require('../assets/pic/myphoto9.jpg'),
    width: 5,
    height: 3,
    title: 'Langkawi, Malaysia',
  },
  {
    src: require('../assets/pic/myphoto12.jpg'),
    width: 5,
    height: 3,
    title: 'Langkawi, Malaysia',
  },
  {
    src: require('../assets/pic/myphoto10.jpg'),
    width: 4,
    height: 5,
    title: 'Harbin, China',
  },
  {
    src: require('../assets/pic/myphoto15.jpg'),
    width: 4,
    height: 5,
    title: 'Hobart, Tasmania, Australia',
  },
  {
    src: require('../assets/pic/myphoto14.jpg'),
    width: 4,
    height: 5,
    title: 'Hobart, Tasmania, Australia',
  },
  {
    src: require('../assets/pic/myphoto11.jpg'),
    width: 4,
    height: 5,
    title: 'Waterloo, New South Wales, Australia',
  },
  {
    src: require('../assets/pic/myphoto4.jpg'),
    width: 4,
    height: 5,
    title: 'Ancliffe, New South Wales, Australia',
  },
  {
    src: require('../assets/pic/myphoto13.jpg'),
    width: 4,
    height: 5,
    title: 'Botany, New South Wales, Australia',
  },
  {
    src: require('../assets/pic/myphoto17.jpg'),
    width: 5,
    height: 3,
    title: 'MONA Museum, Hobart, Tasmania, Australia',
  },
  {
    src: require('../assets/pic/myphoto18.jpg'),
    width: 5,
    height: 3,
    title: 'Hobart, Tasmania, Australia',
  },
];
